version: '3.8'

services:
  inkwell-eureka:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-eureka-server:latest
    container_name: inkwell-eureka
    ports:
      - "8761:8761"
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      resources:
        limits:
          memory: 350M

  inkwell-redis:
    image: redis:alpine
    container_name: inkwell-redis
    networks:
      - inkwell-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - inkwell-network
    deploy:
      resources:
        limits:
          memory: 350M

  api-gateway:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-api-gateway:latest
    container_name: inkwell-gateway
    ports:
      - "8081:8081"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
    deploy:
      resources:
        limits:
          memory: 350M

  auth-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-auth-service:latest
    container_name: inkwell-auth
    ports:
      - "8084:8084"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GATEWAY_URL=${GATEWAY_URL:-https://3.108.190.193.nip.io}
      - FRONTEND_URL=${FRONTEND_URL:-https://inkwell-blogging.netlify.app}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}

    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./uploads:/uploads

  post-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-post-service:latest
    container_name: inkwell-post
    ports:
      - "8082:8082"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${POST_DB_URL}
      - SPRING_REDIS_HOST=inkwell-redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=https://3.108.190.193.nip.io
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./post_uploads:/post_uploads

  comment-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-comment-service:latest
    container_name: inkwell-comment
    ports:
      - "8083:8083"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${POST_DB_URL}
      - SPRING_REDIS_HOST=inkwell-redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL:-https://3.108.190.193.nip.io}
      - FRONTEND_URL=${FRONTEND_URL:-https://inkwell-blogging.netlify.app}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}

    deploy:
      resources:
        limits:
          memory: 250M

  media-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-media-service:latest
    container_name: inkwell-media
    ports:
      - "8087:8087"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${MEDIA_DB}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 250M

  newsletter-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-newsletter-service:latest
    container_name: inkwell-newsletter
    ports:
      - "8086:8086"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${NEWSLETTER_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL:-https://3.108.190.193.nip.io}
      - FRONTEND_URL=${FRONTEND_URL:-https://inkwell-blogging.netlify.app}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

    deploy:
      resources:
        limits:
          memory: 250M

  notification-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-notification-service:latest
    container_name: inkwell-notification
    ports:
      - "8090:8090"
    depends_on:
      - inkwell-eureka
      - rabbitmq
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${NOTIFICATION_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 250M

  payment-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-payment-service:latest
    container_name: inkwell-payment
    ports:
      - "8089:8089"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${PAYMENT_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 250M

  taxonomy-service:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-taxonomy-service:latest
    container_name: inkwell-taxonomy
    ports:
      - "8085:8085"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 250M

  website-controller:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-website-controller:latest
    container_name: inkwell-websitecontroller
    ports:
      - "9001:9001"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 250M

  admin-server:
    image: ${DOCKER_USERNAME:-shifakhan2005}/inkwell-admin-server:latest
    container_name: inkwell-admin
    ports:
      - "9090:9090"
    depends_on:
      - inkwell-eureka
    networks:
      - inkwell-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URL=http://inkwell-eureka:8761/eureka/
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GATEWAY_URL=https://3.108.190.193.nip.io
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  inkwell-network:
    driver: bridge
