server:
  port: 8080 # Changed to 8081 to avoid conflict if you run a microservice on 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        # Prevents "Multiple CORS header" errors in browsers
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: website-controller
          uri: lb://WEBSITE-CONTROLLER
          predicates:
            - Path=/api/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**

        - id: post-service-uploads
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post_uploads/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**

        - id: taxonomy-service
          uri: lb://TAXONOMY-SERVICE
          predicates:
            - Path=/taxonomy/**

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**

        - id: newsletter-service
          uri: lb://NEWSLETTER-SERVICE
          predicates:
            - Path=/newsletter/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

  # Swagger Aggregation Config
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: auth-service
        paths-to-match: /auth/**
      - group: post-service
        paths-to-match: /posts/**
      - group: payment-service
        paths-to-match: /payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true