server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      globalcors:
        add-to-simple-url-handler-mapping: true

        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "https://inkwell-blogging.netlify.app"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      routes:

        - id: website-controller
          uri: lb://WEBSITE-CONTROLLER
          predicates:
            - Path=/api/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/uploads/**,/oauth2/**,/login/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**,/post_uploads/**

        - id: post-service-uploads
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post_uploads/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**

        - id: taxonomy-service
          uri: lb://TAXONOMY-SERVICE
          predicates:
            - Path=/taxonomy/**

        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**

        - id: newsletter-service
          uri: lb://NEWSLETTER-SERVICE
          predicates:
            - Path=/newsletter/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

# Swagger Aggregation
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

    urls:
      - name: Auth Service
        url: /auth/api-docs

      - name: Post Service
        url: /posts/v3/api-docs

      - name: Comment Service
        url: /comments/v3/api-docs

      - name: Taxonomy Service
        url: /taxonomy/v3/api-docs

      - name: Notification Service
        url: /notifications/v3/api-docs

      - name: Payment Service
        url: /payments/v3/api-docs

      - name: Newsletter Service
        url: /newsletter/v3/api-docs

      - name: Media Service
        url: /media/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://inkwell-eureka:8761/eureka/

  instance:
    prefer-ip-address: true