server:
  port: 8082

spring:
  application:
    name: post-service
  config:
    import: optional:file:../.env[.properties]
  
  # ✅ Added Redis Configuration
  data:
    redis:
      host: inkwell-redis
      port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${POST_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://inkwell-eureka:8761/eureka/
  instance:
    prefer-ip-address: true # ✅ Changed to true for better microservice networking
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /posts/v3/api-docs
