server:
  port: 8082

spring:
  application:
    name: post-service
  config:
    import: optional:file:../.env[.properties]
  
  # ✅ ADD THIS SECTION TO FIX THE 413 ERROR
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${POST_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

blog:
  wpm: 200