server:
    port: 8089

spring:
    application:
        name: payment-service
    config:
        # This line tells the service to look one folder up for the .env file
        import: "optional:file:../.env[.properties]"

# ✅ Map the .env variables to the names used in your Java @Value annotations
razorpay:
    key:
        id: ${RAZORPAY_KEY_ID}
        secret: ${RAZORPAY_KEY_SECRET}

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /payments/v3/api-docs
