server:
    port: 8087

spring:
    application:
        name: media-service
    config:
        import: optional:file:../.env[.properties]

    # ✅ Critical for large image uploads
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB

    datasource:
        url: ${MEDIA_DB}
        username: ${DB_USER}
        password: ${DB_PASS}
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
            connection-timeout: 20000
            idle-timeout: 300000
            max-lifetime: 1800000

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        hostname: localhost

springdoc:
  api-docs:
    path: /media/v3/api-docs
