server:
  port: 9001

spring:
  application:
    name: website-controller
  config:
    import: optional:file:../.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://inkwell-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# To see the Feign calls in the console
logging:
  level:
    com.websitecontroller.client: DEBUG